version: '3'

services:
    products-service:
        build: ./service
        volumes:
            - ./service:/usr/src/app
        ports:
            - 5001:80

    products-website:
        image: php:7.0-apache
        volumes:
            - ./website:/var/www/html
        ports:
            - 5000:80
        depends_on:
            - products-service
